

CREATE TABLE SELLER(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(16) NOT NULL
);

CREATE TABLE BUYER(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL
);

CREATE TABLE PROJECT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  DESCRIPTION VARCHAR(256),
  MAX_BUDGET DECIMAL NOT NULL,
  DEADLINE TIMESTAMP NOT NULL,
  SELLER_ID BIGINT NOT NULL,
  OPEN_FOR_AUCTION BOOLEAN NOT NULL,
  foreign key (SELLER_ID) references SELLER(ID)
);

CREATE TABLE BID(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 PROJECT_ID BIGINT NOT NULL,
 BUYER_ID BIGINT NOT NULL,
 AMOUNT DECIMAL NOT NULL,
 foreign key (PROJECT_ID) references PROJECT(ID),
 foreign key (BUYER_ID) references BUYER(ID)
);